Repository AY2122S2-CS2103T-T12-3/tp, pull requests merged in 2022-04, with the labels that each got.

#226 edit help window by constraining size.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/Label.css
Labels: type.Enhancement, priority.Medium, severity.High

#227 Branch fix help documentation
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, priority.High, severity.High

#228 Update cosmetics of buttons in the UI
  src/main/resources/view/MainWindow.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Low

#229 Update UG regarding help feature
  docs/UserGuide.md
Labels: priority.High

#231 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Bug

#233 Added new constraints to name
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug

#234 Fix bug where app cannot close if summarise command is not executed.
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PieChartWindow.java
Labels: type.Bug, severity.High

#236 edit ug to address issue 197
  docs/UserGuide.md
  docs/images/AfterEdit.png
  docs/images/BeforeEdit.png
Labels: type.Enhancement, priority.Medium, severity.VeryLow

#235 Updated add command to indicate which attributes are not unique
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.Medium

#238 Updated behavior of tags attribute
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: severity.Medium

#239 Undo redo bugfix
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/AddressBook.java
Labels: type.Bug, priority.Medium, severity.Medium

#240 Update UG to resolve mock PE issues
  docs/UserGuide.md
  docs/images/Excelscreenshot.png
  docs/images/SummariseExample.png
  docs/images/SummariseExample2.png
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.Medium, severity.VeryLow

#237 Fix Import Format
  docs/UserGuide.md
  docs/images/Excelformat.png
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/model/excel/ImportFileParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#241 Updated UG
  docs/UserGuide.md
Labels: severity.Low

#257 Change implementation of EditCommand execute function
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#258 Update UG to specify details of new Edit implementation
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium

#259 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Bug

#261 Update the method for the non-unique attribute type message
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Bug

#266 Update Jia Le's PPP for milestone 1.4 draft submission
  docs/team/jiale-c.md
Labels: priority.Medium

#265 add sequence diagrams and explanation for Email command
  docs/DeveloperGuide.md
  docs/diagrams/EmailActivityDiagram.puml
  docs/diagrams/EmailSequenceDiagram.puml
  docs/images/EmailActivityDiagram.png
  docs/images/EmailSequenceDiagram.png
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.Medium

#269 Update ppp
  build.gradle
  docs/UserGuide.md
  docs/team/kevinkuo0320.md
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/model/excel/ExcelToJsonConverter.java
  src/main/java/seedu/address/model/excel/ImportFileParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task

#270 Update PPP
  docs/team/tanchinkiat99.md
Labels: type.Task, priority.Medium

#268 Branch update dg
  docs/DeveloperGuide.md
  docs/diagrams/AddClassDiagram.puml
  docs/diagrams/ClearClassDiagram.puml
  docs/diagrams/ClearSequenceDiagram.puml
  docs/images/AddClassDiagram.png
  docs/images/ClearClassDiagram.png
  docs/images/ClearSequenceDiagram.png
  docs/team/dannydakota.md
Labels: type.Task, priority.Medium

#272 Branch update dg
  docs/DeveloperGuide.md
  docs/images/AddSequenceDiagram.png
Labels: priority.Medium

#273 UML diagrams for DG use
  docs/UserGuide.md
  docs/diagrams/PieChartWindowClassDiagram.puml
  docs/diagrams/PieChartWindowSequenceDiagram.puml
  docs/diagrams/SummariseClassDiagram.puml
  docs/diagrams/SummariseFeatureActivityDiagram.puml
  docs/diagrams/SummariseSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/PieChartWindowClassDiagram.png
  docs/images/PieChartWindowSequenceDiagram.png
  docs/images/SummariseClassDiagram.png
  docs/images/SummariseFeatureActivityDiagram.png
  docs/images/SummariseSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/cwq2326.md
  docs/team/dannydakota.md
  docs/team/jiale-c.md
  docs/team/tanchinkiat99.md
  src/main/java/seedu/address/logic/commands/SummariseCommand.java
  src/main/java/seedu/address/ui/ActionBar.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiAlert.java
Labels: priority.Medium

#275 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchiveCommandClassDiagram.puml
  docs/diagrams/ArchiveFeatureActivityDiagram.puml
  docs/diagrams/ArchiveFeatureSequenceDiagram.puml
  docs/diagrams/EditFeatureActivityDiagram.puml
  docs/diagrams/EditFeatureClassDiagram.puml
  docs/diagrams/EditFeatureSequenceDiagram.puml
  docs/diagrams/ResizeCommandClassDiagram.puml
  docs/diagrams/ResizeFeatureSequenceDiagram.puml
  docs/images/ArchiveCommandClassDiagram.png
  docs/images/ArchiveFeatureActivityDiagram.png
  docs/images/ArchiveFeatureSequenceDiagram.png
  docs/images/EditFeatureActivityDiagram.png
  docs/images/EditFeatureClassDiagram.png
  docs/images/EditFeatureSequenceDiagram.png
  docs/images/ResizeCommandClassDiagram.png
  docs/images/ResizeFeatureSequenceDiagram.png
  docs/team/cwq2326.md
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ResizeCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#278 Add test cases for resize command and resize parser class
  src/main/java/seedu/address/logic/commands/ResizeCommand.java
  src/test/java/seedu/address/logic/commands/ResizeCommandTest.java
  src/test/java/seedu/address/logic/parser/ResizeCommandParserTest.java
Labels: priority.Medium

#276 Addition of Help feature to DG and edit EmailSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/EmailSequenceDiagram.puml
  docs/diagrams/HelpActivityDiagram.puml
  docs/diagrams/HelpClassDiagram.puml
  docs/diagrams/HelpSequenceDiagram.puml
  docs/images/EmailSequenceDiagram.png
  docs/images/HelpActivityDiagram.png
  docs/images/HelpClassDiagram.png
  docs/images/HelpSequenceDiagram.png
  docs/team/dannydakota.md
Labels: priority.Medium

#277 Branch jiale dg diagrams
  docs/diagrams/ListFeatureActivityDiagram.puml
  docs/diagrams/ListFeatureClassDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/SummariseClassDiagram.puml
  docs/images/ListFeatureActivityDiagram.png
  docs/images/ListFeatureClassDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/SummariseClassDiagram.png
Labels: priority.Medium

#281 Update UG
  docs/UserGuide.md
  docs/images/RedoCommandScenario.png
  docs/images/UndoCommandScenario.png
Labels: priority.High

#284 Update DG with the suggested format for summarise command and pie chart
  docs/DeveloperGuide.md
Labels: priority.Medium

#290 update DG for help, email and add features
  docs/DeveloperGuide.md
  docs/diagrams/EmailClassDiagram.puml
  docs/images/EmailClassDiagram.png
Labels: priority.Medium

#295 Updates for UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AfterEdit.png
  docs/images/BeforeEdit.png
  docs/images/FAQ_IndexLocation.png
  docs/images/FindScreenshotForUG.png
  docs/images/ListFeatureScreenShot.PNG
  docs/images/RedoCommandScenario.png
  docs/images/UndoCommandScenario.png
  docs/images/UndoRedoFeatureActivityDiagram.png
  docs/team/cwq2326.md
  src/main/java/seedu/address/logic/commands/ResizeCommand.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: priority.High

#296 Branch update dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddClassDiagram.puml
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/DeleteClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ExitActivityDiagram.puml
  docs/diagrams/ExitClassDiagram.puml
  docs/diagrams/ExitCommandSequenceDiagram.puml
  docs/images/AddClassDiagram.png
  docs/images/DeleteActivityDiagram.png
  docs/images/DeleteClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ExitActivityDiagram.png
  docs/images/ExitClassDiagram.png
  docs/images/ExitCommandSequenceDiagram.png
  docs/team/dannydakota.md
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#312 Update syntax for edit feature in UG
  docs/UserGuide.md
Labels: severity.Low

#344 Update UG for CS2101
  docs/UserGuide.md
Labels: type.Bug
