Repository AY2122S2-CS2103T-T12-3/tp, pull requests merged in 2022-03, with the labels that each got.

#44 update commands to cater for new attributes
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#47 Add summarise feature
  src/main/java/seedu/address/logic/commands/SummariseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Faculty.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.High

#46 Update help window by displaying additional information
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High

#58 Add test cases for summarise command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SummariseSequenceDiagram.puml
  docs/images/ModelClassDiagramUpdated.png
  docs/images/SummariseSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/SummariseCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SummariseCommandTest.java
Labels: priority.High

#62 Add block attribute into Person class.
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Block.java
  src/main/java/seedu/address/model/person/CovidStatus.java
  src/main/java/seedu/address/model/person/MatriculationNumber.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#74 Updated Person model attributes that needs to be unique
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#80 Add sequence diagram for AddCommand
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
Labels: priority.High

#75 Add test cases for person package
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SummariseCommand.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Block.java
  src/main/java/seedu/address/model/person/CovidStatus.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Faculty.java
  src/main/java/seedu/address/model/person/MatriculationNumber.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/BlockTest.java
  src/test/java/seedu/address/model/person/CovidStatusTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/FacultyTest.java
  src/test/java/seedu/address/model/person/MatriculationNumberTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#86 Add more pie charts when using SummariseCommand
  src/main/java/seedu/address/logic/commands/SummariseCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PieChartWindow.java
Labels: priority.Medium

#83 add EmailWindow button and window to copy email
  src/main/java/seedu/address/ui/ActionBar.java
  src/main/java/seedu/address/ui/EmailWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EmailWindow.css
  src/main/resources/view/EmailWindow.fxml
  src/main/resources/view/MainWindow.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#89 Edit DeveloperGuide.md for Add Command
  docs/DeveloperGuide.md
  docs/diagrams/AddFeatureActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddFeatureActivityDiagram.png
Labels: type.Task

#92 Add pie chart description into DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ClearFeatureActivityDiagram.puml
  docs/diagrams/SummariseFeatureActivityDiagram.puml
Labels: priority.High

#93 Fix closing application related to emailWindow issue
  src/main/java/seedu/address/ui/MainWindow.java
Labels: severity.High

#96 Edit docs for README and UserGuide.md
  README.md
  docs/UserGuide.md
  docs/images/CopyEmailScreenshot.png
  docs/images/HelpScreenshot.png
Labels: type.Task

#95 Update behavior of pie chart window and enabled assertions in build.gradle
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/PieChartWindowSequenceDiagram.puml
  docs/images/PieChartWindowSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/SummariseCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: severity.Medium

#98 Add edit feature description into DG
  docs/DeveloperGuide.md
  docs/diagrams/AddFeatureActivityDiagram.puml
  docs/diagrams/EditFeatureActivityDiagram.puml
  docs/images/EditFeatureActivityDiagram.png
Labels: priority.High

#100 Add UML diagrams and DG updates
  docs/DeveloperGuide.md
  docs/diagrams/FindFeatureActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ListFeatureActivityDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/SummariseSequenceDiagram.puml
  docs/images/FindFeatureActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/ListFeatureActivityDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/SummariseSequenceDiagram.png
Labels: priority.High

#101 Display response box
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#112 Add archive command
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchiveFeatureActivityDiagram.puml
  docs/diagrams/ArchiveFeatureSequenceDiagram.puml
  docs/images/ArchiveFeatureActivityDiagram.png
  docs/images/ArchiveFeatureSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/data/ArchiveFilesTest/testAddressBook.json
  src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
Labels: type.Story, priority.High

#104 Add UML for Exit Feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ExitFeatureActivityDiagram.jpg
  docs/images/ExitFeatureActivityDiagram.png
  docs/images/ExitFeatureSequenceDiagram.jpg
  docs/images/ListFeatureScreenShot.PNG
Labels: priority.High

#114 Add Command summary and FAQ to user guide
  docs/UserGuide.md
  docs/images/FAQ_IndexLocation.png
Labels: priority.Medium

#113 Update faculty's pre-defined constant
  src/main/java/seedu/address/model/person/Faculty.java
  src/test/java/seedu/address/model/person/FacultyTest.java
Labels: type.Bug

#115 Edit User Guide
  docs/UserGuide.md
  docs/images/FindScreenshotForUG.png
  docs/images/SummariseExample.png
Labels: priority.High

#119 Update Title from "Address App" to "Tracey"
  src/main/resources/view/MainWindow.fxml
Labels: severity.VeryLow

#118 Update function of help window button to open UG
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High

#120 Add a resize display button in the GUI.
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#122 Add on to AddressBookParserTest
  src/main/java/seedu/address/logic/commands/SummariseCommand.java
  src/test/java/seedu/address/logic/commands/SummariseCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#126 Update pie chart UI window
  src/main/java/seedu/address/logic/commands/SummariseCommand.java
  src/main/java/seedu/address/ui/PieChartWindow.java
Labels: priority.High

#127 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Bug

#124 Improve Code Quality
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Block.java
  src/main/java/seedu/address/model/person/CovidStatus.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Faculty.java
  src/main/java/seedu/address/model/person/MatriculationNumber.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/EmailWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: severity.VeryLow

#128 Make User Guide more reader friendly
  docs/UserGuide.md
Labels: type.Story, priority.High

#130 Add undo feature
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/data/ArchiveFilesTest/archive/300322/300322_163209670.json
  src/test/data/ArchiveFilesTest/archive/300322/300322_183523432.json
  src/test/data/ArchiveFilesTest/archive/300322/300322_192852324.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#132 Add redo feature
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#133 Fix bug in Filter feature
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: type.Bug, priority.High, severity.High

#131 Add sample data, change title of shadowJar and edit help window
  build.gradle
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High

#135 Update test cases for commands
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Enhancement, priority.High

#136 Single word commands
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Bug, priority.Medium

#137 Add unit tests for CommandResultTest
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: priority.Medium

#138 Change header from Tracey UG to UG
  docs/UserGuide.md
Labels: severity.VeryLow

#139 Update user guide
  docs/UserGuide.md
  docs/images/FilterScreenshotForUG.png
Labels: type.Task, priority.Medium, severity.Medium

#141 Edit ReadMe and Index.md
  README.md
  docs/images/Ui_ReadMe.png
  docs/index.md
  src/main/resources/images/tracey_icon.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#142 Update glossary in user guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium, severity.Medium

#143 Update Table and Figure numbering and edit grammar.
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#152 Update ResizeCommandParser
  src/main/java/seedu/address/logic/parser/ResizeCommandParser.java
Labels: type.Bug
